name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:18.4.0-alpine3.15
      #env,ports,volumes,options
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
      - name: Send a Slack message
        uses: docker://node:12.14.1-alpine3.10
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Hello Slack!"
