name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:18.4.0-alpine3.15
      #env,ports,volumes,options
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
